# Generated by Django 4.2.7 on 2025-07-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreview',
            name='sentiment_polarity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appreview',
            name='sentiment_subjectivity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
