# Generated by Django 4.2.7 on 2025-07-29 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search_app', '0002_alter_appreview_sentiment_polarity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text="The supervisor who can approve this user's reviews", limit_choices_to={'userprofile__is_supervisor': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
