# Generated by Django 4.2.7 on 2025-07-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0003_userprofile_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='sentiment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userreview',
            name='sentiment_polarity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userreview',
            name='sentiment_subjectivity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
