# Generated by Django 4.2.7 on 2025-07-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0004_userreview_sentiment_userreview_sentiment_polarity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userreview',
            name='has_contradiction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userreview',
            name='rating_sentiment_polarity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userreview',
            name='text_sentiment_polarity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
